# กำหนดเวอร์ชันของ Docker Compose
version: '3.8'

# กำหนด "บริการ" (Services) หรือ Container ที่เราจะสร้าง
services:
  # 1. บริการสำหรับเว็บแอป Flask ของเรา
  web:
    # บอกให้สร้าง Image จาก Dockerfile ในโฟลเดอร์นี้
    build: .
    # ตั้งชื่อ Container ให้สื่อความหมาย
    container_name: my-flask-app
    # เชื่อม Port 8080 ของเครื่องเรา เข้ากับ Port 5000 ของแอป
    ports:
      - "8080:5000"
    # บอกว่าบริการนี้ต้องรอให้ db พร้อมทำงานก่อน ถึงจะเริ่มได้
    depends_on:
      - db

  # 2. บริการสำหรับฐานข้อมูล MySQL
  db:
    # ใช้ Image สำเร็จรูปของ MySQL เวอร์ชัน 8.0
    image: mysql:8.0
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    # ตั้งชื่อ Container
    container_name: my-mysql-db
    # ตั้งค่า Environment Variables ที่จำเป็นสำหรับ MySQL
    environment:
      MYSQL_ROOT_PASSWORD: '123456' # <-- รหัสผ่าน root ของ MySQL
      MYSQL_DATABASE: 'creditbank'   # <-- สร้าง database ชื่อนี้ตอนเริ่ม
    # เก็บข้อมูลของ database ไว้ข้างนอก เพื่อไม่ให้ข้อมูลหายเมื่อปิด Container
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # (Optional) เผื่อเราอยากต่อตรงเข้าไปดูข้อมูลจากข้างนอก
    ports:
      - "3307:3306"

# สร้าง Volume ชื่อ db_data เพื่อใช้เก็บข้อมูลจริงๆ
volumes:
  db_data: